/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\edgar\Downloads\low-poly_sakura_tree\scene.gltf --output src\components\LowPolySakura.jsx --transform --shadows 
Author: SparkyEdit (https://sketchfab.com/SparkyStore)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-sakura-tree-2dd952c43f9c4e8e8f8f70bad038d77d
Title: Low-poly Sakura Tree
*/

import { useGLTF } from "@react-three/drei";

function Sakura(props) {
  const { nodes, materials } = useGLTF("models/low-poly-sakura.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.input_Material001_0.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("models/low-poly-sakura.glb");

export default Sakura;
